name: Deploy MultiK8s

on:
  push:
    branches:
      - main

env:
  SHA: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Test Client
        run: |-
          docker build -t aisimplified/react-test -f ./client/Dockerfile.dev ./client
          docker run --rm -e CI=true aisimplified/react-test npm test

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: top-cascade-446019-e0

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker --quiet

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: multi-cluster-example
          location: europe-west3-a
          project_id: top-cascade-446019-e0

      - name: Build and Push Images
        run: |-
          services=("client" "server" "worker")
          for service in "${services[@]}"; do
            docker build -t aisimplified/multi-${service}-k8s-gh:latest -t aisimplified/multi-${service}-k8s-gh:${{ env.SHA }} -f ./${service}/Dockerfile ./${service} &
          done
          wait
          for service in "${services[@]}"; do
            docker push aisimplified/multi-${service}-k8s-gh:latest &
            docker push aisimplified/multi-${service}-k8s-gh:${{ env.SHA }} &
          done
          wait

      - name: Apply Kubernetes Manifests
        run: |-
          kubectl apply -f k8s
          services=("client" "server" "worker")
          for service in "${services[@]}"; do
            kubectl set image deployments/${service}-deployment ${service}=aisimplified/multi-${service}-k8s-gh:${{ env.SHA }}
          done